"""empty message

Revision ID: 397834fc69b5
Revises: 79ee21ecc618
Create Date: 2025-05-28 19:15:30.282582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397834fc69b5'
down_revision = '79ee21ecc618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('discord', sa.String(length=40), nullable=True))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('preferences',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('nick_name',
               existing_type=sa.VARCHAR(length=21),
               nullable=True)
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_unique_constraint(None, ['discord'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_discord_key', type_='unique')
        batch_op.drop_column('name')
        batch_op.drop_column('age')
        batch_op.drop_column('discord')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('users_discord_key', ['discord'])

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('nick_name',
               existing_type=sa.VARCHAR(length=21),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('preferences',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.drop_column('discord')
        batch_op.drop_column('name')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
