"""empty message

Revision ID: edec223be5b2
Revises: 2031526b03ff
Create Date: 2025-05-23 19:55:49.743542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edec223be5b2'
down_revision = '2031526b03ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=False))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_constraint('profiles_discord_key', type_='unique')
        batch_op.drop_column('discord')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('discord', sa.String(length=40), nullable=False))
        batch_op.create_unique_constraint(None, ['discord'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('discord')
        batch_op.drop_column('name')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('profiles_discord_key', ['discord'])
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('language')

    # ### end Alembic commands ###
